import type { Metadata } from "next";
import "./globals.css";
import jakeImg from "..jakeimg.webp";
 import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Test Run Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Header title={"This is my header"} logoPath={"jakeImg"} />

        {children}

        <Footer>
          This footer, <h2>Banana</h2>
        </Footer>
      </body>
    </html>
  );
}
