import type { Metadata } from "next";
import "./globals.css";
import jakeImg from "@/assets/jakeimg.webp";
 import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Test Run Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Header logoPath={jakeImg.src} />

        {children}

        <Footer>
          This is a footer using react.reactnode for rendering internals
        </Footer>
      </body>
    </html>
  );
}
