import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test Run Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">

       

        {children}

        <footer className=" ">
          This is my footer
        </footer>
      </body>
    </html>
  );
}
